export const events = [
  {
    title: "PyCon US 2026",
    slug: "pycon-us-2026",
    image: "/images/event1.png",
    location: "Pittsburgh, Pennsylvania",
    date: "May 15-17, 2026",
    time: "9:00 AM EDT",
  },
  {
    title: "Google I/O 2026",
    slug: "google-io-2026",
    image: "/images/event2.png",
    location: "Mountain View, California",
    date: "May 19-20, 2026",
    time: "10:00 AM PT",
  },
  {
    title: "Apple WWDC26",
    slug: "apple-wwdc26",
    image: "/images/event3.png",
    location: "Online and Apple Park, Cupertino",
    date: "June 8-12, 2026",
    time: "10:00 AM PT",
  },
  {
    title: "ETHGlobal New York 2026",
    slug: "ethglobal-new-york-2026",
    image: "/images/event4.png",
    location: "New York City, New York",
    date: "June 12-14, 2026",
    time: "9:00 AM ET",
  },
  {
    title: "Devcon 8",
    slug: "devcon-8-mumbai",
    image: "/images/event5.png",
    location: "Mumbai, India",
    date: "November 3-6, 2026",
    time: "9:00 AM IST",
  },
  {
    title: "KubeCon + CloudNativeCon North America 2026",
    slug: "kubecon-cloudnativecon-na-2026",
    image: "/images/event6.png",
    location: "Salt Lake City, Utah",
    date: "November 9-12, 2026",
    time: "9:00 AM MT",
  },
];
